### ISSUE TITLE
Timed task

### ISSUE THREAD

**Issue by monstermichl** [OpenNTF/org.openntf.xsp.jakartaee#508]
Hey Jesse,

just a question. Is there a way to run a function periodically using an annotation?

BR Michel

**Comment by jesse-gallagher** [comment]
Not currently, at least not without implementing a CDI interceptor to do it.

The background there is that the EJB spec _does_ have annotation-based scheduling, I believe, but I've been shying away from adding EJB because it's definitely on its way out. The surrounding specs have been gradually implementing EJB parts, and I imagine that this will show up in Concurrency before too long.

In the mean time, you could do something like have an `@ApplicationScoped` managed bean with a `@PostConstruct`-annotated method that kicks off the schedule, and then make sure that something accesses/injects it early.

**Comment by monstermichl** [comment]
Alright, thank you for the clear explanation. I guess an Agent would be the best approach.
