### ISSUE TITLE
CDI injection for domino objects works at first load then error 500

### ISSUE THREAD

**Issue by DanieleVistalli** [OpenNTF/org.openntf.xsp.jakartaee#93]
[sample-jakartaee.java.txt](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/files/7854816/sample-jakartaee.java.txt)

This sample jax-rs service shows the following behaviour:

1- Saving the code (and app is reloaded)
2- Invoke service works correctly and objects are available (browser invocation of the URL)
3- Subsequent invocation fail with error 500

As soon as I reload the app (or save the code triggering a reload) it works, but just once.

If I take away the CDI annotations it works repeatedly.

I've tried keeping a single injection only but the behaviour is the same.

I'm going to check server logs and investigate which kind fo exception is being raised.

**Comment by jesse-gallagher** [comment]
Do they fail specifically with "Object has been removed or recycled"? If so, it may be this one: https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/83 . I'm mulling over options for how to deal with that... I'm not sure if there's a good way for me to signal in CDI that the produced objects shouldn't themselves be retained like that, so I may change it so that it emits `Supplier<Database>`, etc. instead of `Database` directly.

**Comment by DanieleVistalli** [comment]
I am going to investigage xml logs and report back. I just wanted to start tracking the thing. Don't spend time on it as long as I don't bringe better information. Thanks for the quick turnaround.

**Comment by jesse-gallagher** [comment]
This, and the multi-request-problem issues in general, is backed up by injecting a `RequestScoped` bean into a service: though in XPages those are renewed each time, that's not the case with JAX-RS.
